[package]
name = "rssh"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
dioxus = { version = "0.7.9", features = ["router"] }
dioxus-fullstack = "0.7.9"
dioxus-web = "0.7.9"
dirs = "6.0.0"
futures = "0.3.32"
jni = "0.22.4"
miniflux_api = "0.8.0"
reqwest = { version = "0.13.3", features = ["native-tls"] }
rusqlite = { version = "0.39.0", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
strum = { version = "0.28.0", features = ["derive"] }
tokio = "1.52.3"
tracing = "0.1.44"

[dev-dependencies]
pretty_assertions = "1.4.1"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "unwind"
lto = true
codegen-units = 1
strip = true

[profile.bench]
opt-level = 3
debug = false
