use crate::prelude::FeedNode;

/// RSS Category is a group of feeds
#[derive(Clone, PartialEq, Debug)]
pub struct Category {
    /// ID
    pub id: i64,
    /// Title
    pub label: String,
    /// Custom given color generated by label
    pub color: String,
}

/// CategoryNode is an helper to organized content for Category  
#[derive(Clone, PartialEq)]
pub struct CategoryNode {
    /// Category related
    pub category: Category,
    /// Information if Category as been expanded
    pub expanded: bool,
    /// Feeds related
    pub feeds: Option<Vec<FeedNode>>,
}
