use crate::Article;

pub fn sample_articles() -> Vec<Article> {
    vec![
        Article {
            id: "a1".into(),
            source: "hacker_news".into(),
            source_color: "#d7875f".into(),
            title: "Rust 1.85 released with async traits".into(),
            snippet: "Major release brings stabilized async fn in tra…".into(),
            timestamp: "2h".into(),
            is_read: false,
            is_starred: false,
        },
        Article {
            id: "a2".into(),
            source: "lobste_rs".into(),
            source_color: "#d75f5f".into(),
            title: "Why we ditched microservices".into(),
            snippet: "After 3 years running 47 services we moved to…".into(),
            timestamp: "5h".into(),
            is_read: false,
            is_starred: true,
        },
        Article {
            id: "a3".into(),
            source: "ars_technica".into(),
            source_color: "#e5c07b".into(),
            title: "AMD's new GPU architecture detailed".into(),
            snippet: "RDNA 5 promises 60% perf-per-watt gains over…".into(),
            timestamp: "7h".into(),
            is_read: false,
            is_starred: false,
        },
        Article {
            id: "a4".into(),
            source: "phoronix".into(),
            source_color: "#87d75f".into(),
            title: "Linux 6.20 brings new EEVDF scheduler".into(),
            snippet: "Latest kernel ships with significant scheduler…".into(),
            timestamp: "11h".into(),
            is_read: false,
            is_starred: false,
        },
        Article {
            id: "a5".into(),
            source: "dioxus_blog".into(),
            source_color: "#c678dd".into(),
            title: "Dioxus 0.7: native Android UI".into(),
            snippet: "New release adds first-class Android support w…".into(),
            timestamp: "14h".into(),
            is_read: true,
            is_starred: false,
        },
        Article {
            id: "a6".into(),
            source: "xkcd".into(),
            source_color: "#5fafd7".into(),
            title: "Bug Report".into(),
            snippet: "A new comic strip about debugging in producti…".into(),
            timestamp: "1d".into(),
            is_read: false,
            is_starred: false,
        },
        Article {
            id: "a7".into(),
            source: "hacker_news".into(),
            source_color: "#d7875f".into(),
            title: "The state of WebAssembly 2026".into(),
            snippet: "Survey results from 4,200 developers reveal…".into(),
            timestamp: "1d".into(),
            is_read: true,
            is_starred: false,
        },
    ]
}
